site_name: Qi Tang
site_url: https://tangqi.github.io
docs_dir: 'src'

markdown_extensions:
- extra  # allow markdown in <div markdown="1">
- fenced_code  # GitHub style code blocks, e.g. ```python, see https://highlightjs.readthedocs.org/en/latest/css-classes-reference.html for a list of languages
- footnotes
- attr_list  # Allow us to add link attributes
- sane_lists # Allow list starting from an arbitrary number

nav:
- Home: index.md
- News: news.md
- Team: team.md
- Research:
  - 'High-performance computing': hpc.md
  - 'Scientific computing and simulation': computing.md
  - 'Scientific machine learning': ml.md
- Publications: publications.md
- CV: cv.md
- Teaching: 
  - 'Spring 2025': spring-2025.md
  - 'Fall 2025': fall-2025.md


theme:
  name: mkdocs  # required. Can be anything as long as custom_dir is set correctly below
  custom_dir: template

extra:
  include_next_prev: false  # turn off next/previous buttons
